/** Every public route. Kept in one place so a11y, screenshots and SEO checks agree. */
export const ROUTES = [
  '/',
  '/uslugi',
  '/urzadzenia',
  '/urzadzenia/piece-konwekcyjno-parowe',
  '/urzadzenia/zmywarki-gastronomiczne',
  '/urzadzenia/ekspresy-i-urzadzenia-barowe',
  '/urzadzenia/urzadzenia-chlodnicze',
  '/urzadzenia/urzadzenia-grzewcze',
  '/uslugi/jakie-uslugi-swiadczymy',
  '/uslugi/jakie-uslugi-swiadczymy/przeglady-okresowe',
  '/uslugi/jakie-uslugi-swiadczymy/naprawy-awaryjne',
  '/uslugi/jakie-uslugi-swiadczymy/instalacje-i-deinstalacje',
  '/uslugi/jakie-uslugi-swiadczymy/marki-naprawianego-sprzetu',
  '/uslugi/gdzie-naprawiamy',
  '/uslugi/serwis-unic',
  '/uslugi/serwis-stalgast',
  '/uslugi/serwis-firex',
  '/uslugi/serwis-convotherm',
  '/o-firmie',
  '/centrum-wiedzy',
  '/kontakt',
  '/polityka-cookies',
] as const
